name: fourth_action

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: 'Nombre del usuario'
        required: false
        default: 'Mundo'
      age:
        type: boolean
        description: '¿Es mayor de edad?'
        required: false
        default:  false
  
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: echo "Hello, world!"
    - name: Información adicional
      run: echo "Este es el segundo paso del primer job"
      
  segundo_job:
    runs-on: ubuntu-latest
    needs: say_hello
    steps:
    - name: Primer paso
      run: echo "Este es el primer paso del segundo job"
    - name: Segundo paso
      run: echo ${{ github.event.inputs.debug_mode }}