name: Python Tests on PR

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run Linters
      run: |
        flake8 code/python

    - name: Run Tests
      run: |
        cd code/python
        python -m unittest test_calculator.py
    
    - name: Run Tests with Coverage
      run: |
        cd code/python
        coverage run -m unittest test_calculator.py
        coverage report -m
        coverage html
        coverage xml
    